name: gitleaks

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow loaded"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # lets gitleaks scan history if needed

      - name: Run gitleaks (CLI)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz \
            | tar -xz
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version
          gitleaks detect --source . --redact --verbose
